2019-12-31 10:36:48: Unexpected exception
Traceback (most recent call last):
  File "G:\AI\MahjongAI-master\main.py", line 17, in connect_and_play
    return client.start_game()
  File "G:\AI\MahjongAI-master\client\tenhou_client.py", line 100, in start_game
    if not self._looking_for_a_game():
  File "G:\AI\MahjongAI-master\client\tenhou_client.py", line 220, in _looking_for_a_game
    msgs = self._get()
  File "G:\AI\MahjongAI-master\client\tenhou_client.py", line 683, in _get
    msgs = self.skt.recv(2048).decode('utf-8')
ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。
